export Home from './Home.js';
export Navgitor from './Navgitor';
export BascRoute from './BascRoute';
export Content from './Content';
export Blocking from './Blocking';
export Miss from './Miss';
export Nomatch from './Nomatch';
export Query from './Query';
export Ruqice from './ruqirs'